name: Deploy
on: push
jobs:
  deploy_maps:
    if: github.repository_owner == 'graphhopper'
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --fail -H "Authorization: token ${{ secrets.PRIVATE_GITHUB_ACCESS_TOKEN }}" \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            "https://api.github.com/repos/${{ secrets.DEPLOY_REPO }}/dispatches" \
            -d '{"event_type": "deploy-maps", "client_payload": {"branch": "${{ github.ref_name }}", "commit": "${{ github.sha }}"}}'
