name: Test and Build
on: push

jobs:
  test_and_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: lts/gallium

      - name: Test and Build
        run: |
          npm ci
          npm run test
          npm run build
